//CREATE appointment
###
POST http://localhost:3000/appointment/create
Content-Type: application/json

{
    "userdoctor": "DrGuetts",
    "namepet":"Matias",
    "userowner":"FreddyGM",
    "dateapp":"2022/05/13",
    "hourapp":"14:30"
}

//GET USERS appointment
###
GET http://localhost:3000/appointment/appointmentall
Content-Type: application/json


//GET appointment by date
###
GET http://localhost:3000/appointment/date/2022-05-13
Content-Type: application/json

//GET appointment by doctor
###
GET http://localhost:3000/appointment/doctor/DrGuetts
Content-Type: application/json

//GET  appointment by User
###
GET http://localhost:3000/appointment/owner/FreddyGM
Content-Type: application/json

//UPDATE USERS
###
PATCH http://localhost:3000/appointment/638bd514212e2028fc9c94b6
Content-Type: application/json

{
    "dateapp":"2022-07-07"
}

//DELETE USERS
###
DELETE http://localhost:3000/appointment/638bd514212e2028fc9c94b6
Content-Type: application/json
